apiVersion: argoproj.io/v1alpha2
kind: Application
metadata:
  name: nodejs-app
spec:
  project: default
  source:
    repoURL: https://github.com/cynogen127/nodejs-k8.git
    path: .
  destination:
    namespace: argocd
  syncPolicy:
    automated:
      prune: true
  ignoreDifferences:
    - group: apps
      kind: Deployment
    - group: "argocd"
      kind: Service
  healthChecks:
    - readinessProbe:
        httpGet:
          path: /
          port: 8080
      livenessProbe:
        httpGet:
          path: /
          port: 8080
  deployment:
    manifests:
    - apiVersion: apps/v1
      kind: Deployment
      metadata:
      
        name: nodejs-app
      spec:
        replicas: 1
        selector:
          matchLabels:
            app: nodejs-app
        template:
          metadata:
            labels:
              app: nodejs-app
          spec:
            containers:
            - name: nodejs-app
              image: node:16-alpine
              ports:
              - containerPort: 8080
              command: ["node", "index.js"]
              volumeMounts:
              - name: npm-cache
                mountPath: /root/.npm

      volumes:
      - name: npm-cache
        emptyDir: {}
    - apiVersion: v1
      kind: Service
      metadata:
        name: nodejs-app
      spec:
        type: ClusterIP
        selector:
          app: nodejs-app
        ports:
        - protocol: TCP
          port: 80
          targetPort: 8080

