apiVersion: apps/v1
kind: Deployment
metadata:
  name: nodejs-app
  namespace: bjex
  labels:
    app: nodejs-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nodejs
  template:
    metadata:
      labels:
        app: nodejs
    spec:
      nodeSelector:
        "beta.kubernetes.io/os": linux
      containers:
        - name: nodejs-app
          image: judi2021/fatah
          ports:
            - name: http
              containerPort: 3000

