apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- deployment.yaml
patches:
- target:
    kind: Deployment
    name: nodejs-app
  patch: |-
    - op: replace
      path: "/spec/template/spec/containers/0/image"
      value: "alpine:latest"

    - op: add
      path: /spec/template/spec/containers/0/volumeMounts
      value:
        - name: index-js
          mountPath: /app/index.js
          subPath: index.js
          readOnly: true


